import type { User, Post, Comment, Notification, Status, Chat } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';
import { sub } from 'date-fns';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const users: User[] = [
  {
    id: 'user-1',
    uid: 'user-1',
    username: 'vibemaster',
    name: 'Alex Doe',
    firstName: 'Alex',
    lastName: 'Doe',
    avatarUrl: findImage('avatar-1'),
    bio: 'Just here for the vibes ✨',
    followersCount: 1200,
    followingCount: 150,
  },
  {
    id: 'user-2',
    uid: 'user-2',
    username: 'pixelperfect',
    name: 'Jessica Smith',
    firstName: 'Jessica',
    lastName: 'Smith',
    avatarUrl: findImage('avatar-2'),
    bio: 'Capturing moments, one pixel at a time. 📸',
    followersCount: 5430,
    followingCount: 200,
  },
  {
    id: 'user-3',
    uid: 'user-3',
    username: 'soundwave',
    name: 'Chris Lee',
    firstName: 'Chris',
    lastName: 'Lee',
    avatarUrl: findImage('avatar-3'),
    bio: 'DJ & Producer. Music is my life.',
    followersCount: 25000,
    followingCount: 50,
  },
  {
    id: 'user-4',
    uid: 'user-4',
    username: 'janedoe',
    name: 'Jane Doe',
    firstName: 'Jane',
    lastName: 'Doe',
    avatarUrl: findImage('avatar-4'),
    bio: 'Exploring the world and sharing my journey.',
    followersCount: 800,
    followingCount: 300,
  },
  {
    id: 'user-5',
    uid: 'user-5',
    username: 'creativecortex',
    name: 'Mia Wong',
    firstName: 'Mia',
    lastName: 'Wong',
    avatarUrl: findImage('avatar-5'),
    bio: 'Digital artist and storyteller.',
    followersCount: 12000,
    followingCount: 500,
  }
];

export const currentUser = users[0];

export const posts: Post[] = [
  {
    id: 'post-1',
    author: users[1],
    authorId: users[1].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    mediaType: 'video',
    caption: 'Cyberpunk city nights are a different kind of magic.',
    likesCount: 234,
    commentsCount: 2,
    createdAt: '3h ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-2',
    author: users[2],
    authorId: users[2].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    mediaType: 'video',
    caption: 'Finding peace in nature\'s embrace. Perfect spot to meditate and create new sounds.',
    likesCount: 540,
    commentsCount: 0,
    createdAt: '5h ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-3',
    author: users[3],
    authorId: users[3].id,
    mediaUrl: findImage('post-3'),
    mediaType: 'image',
    caption: 'Playing with colors and shapes. What do you see?',
    likesCount: 120,
    commentsCount: 0,
    createdAt: '1d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-4',
    author: users[4],
    authorId: users[4].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    mediaType: 'video',
    caption: 'Street style in the city that never sleeps.',
    likesCount: 890,
    commentsCount: 1,
    createdAt: '2d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-5',
    author: users[0],
    authorId: users[0].id,
    mediaUrl: findImage('post-5'),
    mediaType: 'image',
    caption: 'Brunch goals! This was too good not to share.',
    likesCount: 450,
    commentsCount: 0,
    createdAt: '3d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-6',
    author: users[1],
    authorId: users[1].id,
    mediaUrl: findImage('post-6'),
    mediaType: 'image',
    caption: 'Lost in the beauty of this place. Unforgettable.',
    likesCount: 621,
    commentsCount: 0,
    createdAt: '3d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
];

export const mockNotifications: Notification[] = [
    { id: 'notif-1', type: 'follow', fromUser: users[2], read: false, createdAt: sub(new Date(), { minutes: 5 }) },
    { id: 'notif-2', type: 'like', fromUser: users[1], post: posts[4], read: false, createdAt: sub(new Date(), { minutes: 30 }) },
    { id: 'notif-3', type: 'comment', fromUser: users[3], post: posts[4], commentText: "So stylish! ✨", read: true, createdAt: sub(new Date(), { hours: 2 }) },
    { id: 'notif-4', type: 'like', fromUser: users[4], post: posts[0], read: true, createdAt: sub(new Date(), { hours: 12 }) },
    { id: 'notif-5', type: 'follow', fromUser: users[4], read: true, createdAt: sub(new Date(), { days: 1 }) },
];

export const mockStatuses: Status[] = [
    { id: 'status-1', author: users[1], mediaUrl: findImage('status-1'), mediaType: 'image', createdAt: new Date() },
    { id: 'status-2', author: users[2], mediaUrl: findImage('status-2'), mediaType: 'image', createdAt: new Date() },
    { id: 'status-3', author: users[3], mediaUrl: findImage('status-3'), mediaType: 'image', createdAt: new Date() },
    { id: 'status-4', author: users[4], mediaUrl: findImage('status-4'), mediaType: 'image', createdAt: new Date() },
];

export const mockChats: Chat[] = [
    { 
        id: 'chat-1',
        participants: [currentUser, users[1]],
        lastMessage: 'Hey, saw your latest post, amazing shot!',
        lastMessageTimestamp: sub(new Date(), { hours: 1 }),
        unreadCount: 2,
    },
    { 
        id: 'chat-2',
        participants: [currentUser, users[3]],
        lastMessage: 'Let\'s collab sometime!',
        lastMessageTimestamp: sub(new Date(), { days: 1 }),
        unreadCount: 0,
    },
     { 
        id: 'chat-3',
        participants: [currentUser, users[4]],
        lastMessage: 'Just wanted to say I love your work.',
        lastMessageTimestamp: sub(new Date(), { days: 3 }),
        unreadCount: 0,
    },
];
