import type { User, Post, Comment } from '@/lib/types';
import { PlaceHolderImages } from '@/lib/placeholder-images';

const findImage = (id: string) => PlaceHolderImages.find(img => img.id === id)?.imageUrl || '';

export const users: User[] = [
  {
    id: 'user-1',
    uid: 'user-1',
    username: 'vibemaster',
    name: 'Alex Doe',
    firstName: 'Alex',
    lastName: 'Doe',
    avatarUrl: findImage('avatar-1'),
    bio: 'Just here for the vibes ✨',
    followersCount: 1200,
    followingCount: 150,
  },
  {
    id: 'user-2',
    uid: 'user-2',
    username: 'pixelperfect',
    name: 'Jessica Smith',
    firstName: 'Jessica',
    lastName: 'Smith',
    avatarUrl: findImage('avatar-2'),
    bio: 'Capturing moments, one pixel at a time. 📸',
    followersCount: 5430,
    followingCount: 200,
  },
  {
    id: 'user-3',
    uid: 'user-3',
    username: 'soundwave',
    name: 'Chris Lee',
    firstName: 'Chris',
    lastName: 'Lee',
    avatarUrl: findImage('avatar-3'),
    bio: 'DJ & Producer. Music is my life.',
    followersCount: 25000,
    followingCount: 50,
  },
  {
    id: 'user-4',
    uid: 'user-4',
    username: 'janedoe',
    name: 'Jane Doe',
    firstName: 'Jane',
    lastName: 'Doe',
    avatarUrl: findImage('avatar-4'),
    bio: 'Exploring the world and sharing my journey.',
    followersCount: 800,
    followingCount: 300,
  },
  {
    id: 'user-5',
    uid: 'user-5',
    username: 'creativecortex',
    name: 'Mia Wong',
    firstName: 'Mia',
    lastName: 'Wong',
    avatarUrl: findImage('avatar-5'),
    bio: 'Digital artist and storyteller.',
    followersCount: 12000,
    followingCount: 500,
  }
];

export const currentUser = users[0];

const commentsForPost1: Comment[] = [
    { id: 'comment-1-1', authorId: 'user-1', postId: 'post-1', author: users[0], text: 'This is amazing! 🔥', createdAt: '2h ago' },
    { id: 'comment-1-2', authorId: 'user-2', postId: 'post-1', author: users[2], text: 'Wow, what a shot!', createdAt: '1h ago' },
];

const commentsForPost4: Comment[] = [
    { id: 'comment-4-1', authorId: 'user-2', postId: 'post-4', author: users[1], text: 'Love this look!', createdAt: '2d ago' },
];


export const posts: Post[] = [
  {
    id: 'post-1',
    author: users[1],
    authorId: users[1].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    mediaType: 'video',
    caption: 'Cyberpunk city nights are a different kind of magic.',
    likesCount: 234,
    commentsCount: commentsForPost1.length,
    createdAt: '3h ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-2',
    author: users[2],
    authorId: users[2].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    mediaType: 'video',
    caption: 'Finding peace in nature\'s embrace. Perfect spot to meditate and create new sounds.',
    likesCount: 540,
    commentsCount: 0,
    createdAt: '5h ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-3',
    author: users[3],
    authorId: users[3].id,
    mediaUrl: findImage('post-3'),
    mediaType: 'image',
    caption: 'Playing with colors and shapes. What do you see?',
    likesCount: 120,
    commentsCount: 0,
    createdAt: '1d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-4',
    author: users[4],
    authorId: users[4].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    mediaType: 'video',
    caption: 'Street style in the city that never sleeps.',
    likesCount: 890,
    commentsCount: commentsForPost4.length,
    createdAt: '2d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-5',
    author: users[0],
    authorId: users[0].id,
    mediaUrl: findImage('post-5'),
    mediaType: 'image',
    caption: 'Brunch goals! This was too good not to share.',
    likesCount: 450,
    commentsCount: 0,
    createdAt: '3d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-6',
    author: users[1],
    authorId: users[1].id,
    mediaUrl: findImage('post-6'),
    mediaType: 'image',
    caption: 'Lost in the beauty of this place. Unforgettable.',
    likesCount: 621,
    commentsCount: 0,
    createdAt: '3d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-7',
    author: users[2],
    authorId: users[2].id,
    mediaUrl: findImage('post-7'),
    mediaType: 'image',
    caption: 'My best co-worker.',
    likesCount: 1023,
    commentsCount: 0,
    createdAt: '4d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
  {
    id: 'post-8',
    author: users[0],
    authorId: users[0].id,
    mediaUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    mediaType: 'video',
    caption: 'Pushing the limits.',
    likesCount: 188,
    commentsCount: 0,
    createdAt: '4d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
    {
    id: 'post-9',
    author: users[3],
    authorId: users[3].id,
    mediaUrl: findImage('post-9'),
    mediaType: 'image',
    caption: 'Lines and shadows.',
    likesCount: 341,
    commentsCount: 0,
    createdAt: '5d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  },
    {
    id: 'post-10',
    author: users[4],
    authorId: users[4].id,
    mediaUrl: findImage('post-10'),
    mediaType: 'image',
    caption: 'Late night coding session. #developerlife',
    likesCount: 98,
    commentsCount: 0,
    createdAt: '5d ago',
    privacy: 'public',
    allowComments: true,
    allowDuet: true,
    allowStitch: true,
  }
];
